extract = 'total_dyn_inst: (\d+)'
benchmarks = '../examples/test/lvn/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python3 ../elamdf/lvn.py",
    "python3 ../elamdf/dead.py",
    "brili -p {args}",
]
